"""rent

Revision ID: e723a8e72dac
Revises: 0dc3a04ba5e7
Create Date: 2023-04-11 09:52:19.833140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e723a8e72dac'
down_revision = '0dc3a04ba5e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rent', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.drop_column('rent')

    # ### end Alembic commands ###
